services:
  node-worker-a:
    build: ./node-worker
    restart: always
    environment:
      - WORKER_ID=a

  node-worker-b:
    build: ./node-worker
    restart: always
    environment:
      - WORKER_ID=b

  node-worker-c:
    build: ./node-worker
    restart: always
    environment:
      - WORKER_ID=c

  node-worker-d:
    build: ./node-worker
    restart: always
    environment:
      - WORKER_ID=d

  nginx-balancer:
    image: nginx:stable
    volumes: 
      - ./nginx-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - node-worker-a
      - node-worker-b
      - node-worker-c
      - node-worker-d
    restart: always

  

  